import Foundation

enum TrackerData {
    static func items(for type: TrackerType) -> [TrackerItem] {
        switch type {
        case .countries:
            return countries
        case .states:
            return usStatesOnly
        case .continents:
            return continents
        case .subwaySystems:
            return subwaySystems
        case .nationalParks:
            return usNationalParks
        }
    }

    // MARK: - Countries (static list)

    // ISO-3166 alpha-2 codes for stable IDs.
    static let countries: [TrackerItem] = [
        TrackerItem(id: "AF", name: "Afghanistan"),
        TrackerItem(id: "AL", name: "Albania"),
        TrackerItem(id: "DZ", name: "Algeria"),
        TrackerItem(id: "AS", name: "American Samoa"),
        TrackerItem(id: "AD", name: "Andorra"),
        TrackerItem(id: "AO", name: "Angola"),
        TrackerItem(id: "AI", name: "Anguilla"),
        TrackerItem(id: "AQ", name: "Antarctica"),
        TrackerItem(id: "AG", name: "Antigua and Barbuda"),
        TrackerItem(id: "AR", name: "Argentina"),
        TrackerItem(id: "AM", name: "Armenia"),
        TrackerItem(id: "AW", name: "Aruba"),
        TrackerItem(id: "AU", name: "Australia"),
        TrackerItem(id: "AT", name: "Austria"),
        TrackerItem(id: "AZ", name: "Azerbaijan"),
        TrackerItem(id: "BS", name: "Bahamas"),
        TrackerItem(id: "BH", name: "Bahrain"),
        TrackerItem(id: "BD", name: "Bangladesh"),
        TrackerItem(id: "BB", name: "Barbados"),
        TrackerItem(id: "BY", name: "Belarus"),
        TrackerItem(id: "BE", name: "Belgium"),
        TrackerItem(id: "BZ", name: "Belize"),
        TrackerItem(id: "BJ", name: "Benin"),
        TrackerItem(id: "BM", name: "Bermuda"),
        TrackerItem(id: "BT", name: "Bhutan"),
        TrackerItem(id: "BO", name: "Bolivia"),
        TrackerItem(id: "BA", name: "Bosnia and Herzegovina"),
        TrackerItem(id: "BW", name: "Botswana"),
        TrackerItem(id: "BR", name: "Brazil"),
        TrackerItem(id: "IO", name: "British Indian Ocean Territory"),
        TrackerItem(id: "BN", name: "Brunei"),
        TrackerItem(id: "BG", name: "Bulgaria"),
        TrackerItem(id: "BF", name: "Burkina Faso"),
        TrackerItem(id: "BI", name: "Burundi"),
        TrackerItem(id: "KH", name: "Cambodia"),
        TrackerItem(id: "CM", name: "Cameroon"),
        TrackerItem(id: "CA", name: "Canada"),
        TrackerItem(id: "CV", name: "Cape Verde"),
        TrackerItem(id: "KY", name: "Cayman Islands"),
        TrackerItem(id: "CF", name: "Central African Republic"),
        TrackerItem(id: "TD", name: "Chad"),
        TrackerItem(id: "CL", name: "Chile"),
        TrackerItem(id: "CN", name: "China"),
        TrackerItem(id: "CX", name: "Christmas Island"),
        TrackerItem(id: "CC", name: "Cocos (Keeling) Islands"),
        TrackerItem(id: "CO", name: "Colombia"),
        TrackerItem(id: "KM", name: "Comoros"),
        TrackerItem(id: "CG", name: "Congo"),
        TrackerItem(id: "CD", name: "Congo (DRC)"),
        TrackerItem(id: "CK", name: "Cook Islands"),
        TrackerItem(id: "CR", name: "Costa Rica"),
        TrackerItem(id: "CI", name: "Côte d’Ivoire"),
        TrackerItem(id: "HR", name: "Croatia"),
        TrackerItem(id: "CU", name: "Cuba"),
        TrackerItem(id: "CW", name: "Curaçao"),
        TrackerItem(id: "CY", name: "Cyprus"),
        TrackerItem(id: "CZ", name: "Czechia"),
        TrackerItem(id: "DK", name: "Denmark"),
        TrackerItem(id: "DJ", name: "Djibouti"),
        TrackerItem(id: "DM", name: "Dominica"),
        TrackerItem(id: "DO", name: "Dominican Republic"),
        TrackerItem(id: "EC", name: "Ecuador"),
        TrackerItem(id: "EG", name: "Egypt"),
        TrackerItem(id: "SV", name: "El Salvador"),
        TrackerItem(id: "GQ", name: "Equatorial Guinea"),
        TrackerItem(id: "ER", name: "Eritrea"),
        TrackerItem(id: "EE", name: "Estonia"),
        TrackerItem(id: "SZ", name: "Eswatini"),
        TrackerItem(id: "ET", name: "Ethiopia"),
        TrackerItem(id: "FK", name: "Falkland Islands"),
        TrackerItem(id: "FO", name: "Faroe Islands"),
        TrackerItem(id: "FJ", name: "Fiji"),
        TrackerItem(id: "FI", name: "Finland"),
        TrackerItem(id: "FR", name: "France"),
        TrackerItem(id: "GF", name: "French Guiana"),
        TrackerItem(id: "PF", name: "French Polynesia"),
        TrackerItem(id: "TF", name: "French Southern Territories"),
        TrackerItem(id: "GA", name: "Gabon"),
        TrackerItem(id: "GM", name: "Gambia"),
        TrackerItem(id: "GE", name: "Georgia"),
        TrackerItem(id: "DE", name: "Germany"),
        TrackerItem(id: "GH", name: "Ghana"),
        TrackerItem(id: "GI", name: "Gibraltar"),
        TrackerItem(id: "GR", name: "Greece"),
        TrackerItem(id: "GL", name: "Greenland"),
        TrackerItem(id: "GD", name: "Grenada"),
        TrackerItem(id: "GP", name: "Guadeloupe"),
        TrackerItem(id: "GU", name: "Guam"),
        TrackerItem(id: "GT", name: "Guatemala"),
        TrackerItem(id: "GG", name: "Guernsey"),
        TrackerItem(id: "GN", name: "Guinea"),
        TrackerItem(id: "GW", name: "Guinea-Bissau"),
        TrackerItem(id: "GY", name: "Guyana"),
        TrackerItem(id: "HT", name: "Haiti"),
        TrackerItem(id: "HN", name: "Honduras"),
        TrackerItem(id: "HK", name: "Hong Kong"),
        TrackerItem(id: "HU", name: "Hungary"),
        TrackerItem(id: "IS", name: "Iceland"),
        TrackerItem(id: "IN", name: "India"),
        TrackerItem(id: "ID", name: "Indonesia"),
        TrackerItem(id: "IR", name: "Iran"),
        TrackerItem(id: "IQ", name: "Iraq"),
        TrackerItem(id: "IE", name: "Ireland"),
        TrackerItem(id: "IM", name: "Isle of Man"),
        TrackerItem(id: "IL", name: "Israel"),
        TrackerItem(id: "IT", name: "Italy"),
        TrackerItem(id: "JM", name: "Jamaica"),
        TrackerItem(id: "JP", name: "Japan"),
        TrackerItem(id: "JE", name: "Jersey"),
        TrackerItem(id: "JO", name: "Jordan"),
        TrackerItem(id: "KZ", name: "Kazakhstan"),
        TrackerItem(id: "KE", name: "Kenya"),
        TrackerItem(id: "KI", name: "Kiribati"),
        TrackerItem(id: "XK", name: "Kosovo"),
        TrackerItem(id: "KW", name: "Kuwait"),
        TrackerItem(id: "KG", name: "Kyrgyzstan"),
        TrackerItem(id: "LA", name: "Laos"),
        TrackerItem(id: "LV", name: "Latvia"),
        TrackerItem(id: "LB", name: "Lebanon"),
        TrackerItem(id: "LS", name: "Lesotho"),
        TrackerItem(id: "LR", name: "Liberia"),
        TrackerItem(id: "LY", name: "Libya"),
        TrackerItem(id: "LI", name: "Liechtenstein"),
        TrackerItem(id: "LT", name: "Lithuania"),
        TrackerItem(id: "LU", name: "Luxembourg"),
        TrackerItem(id: "MO", name: "Macao"),
        TrackerItem(id: "MG", name: "Madagascar"),
        TrackerItem(id: "MW", name: "Malawi"),
        TrackerItem(id: "MY", name: "Malaysia"),
        TrackerItem(id: "MV", name: "Maldives"),
        TrackerItem(id: "ML", name: "Mali"),
        TrackerItem(id: "MT", name: "Malta"),
        TrackerItem(id: "MH", name: "Marshall Islands"),
        TrackerItem(id: "MQ", name: "Martinique"),
        TrackerItem(id: "MR", name: "Mauritania"),
        TrackerItem(id: "MU", name: "Mauritius"),
        TrackerItem(id: "YT", name: "Mayotte"),
        TrackerItem(id: "MX", name: "Mexico"),
        TrackerItem(id: "FM", name: "Micronesia"),
        TrackerItem(id: "MD", name: "Moldova"),
        TrackerItem(id: "MC", name: "Monaco"),
        TrackerItem(id: "MN", name: "Mongolia"),
        TrackerItem(id: "ME", name: "Montenegro"),
        TrackerItem(id: "MS", name: "Montserrat"),
        TrackerItem(id: "MA", name: "Morocco"),
        TrackerItem(id: "MZ", name: "Mozambique"),
        TrackerItem(id: "MM", name: "Myanmar"),
        TrackerItem(id: "NA", name: "Namibia"),
        TrackerItem(id: "NR", name: "Nauru"),
        TrackerItem(id: "NP", name: "Nepal"),
        TrackerItem(id: "NL", name: "Netherlands"),
        TrackerItem(id: "NC", name: "New Caledonia"),
        TrackerItem(id: "NZ", name: "New Zealand"),
        TrackerItem(id: "NI", name: "Nicaragua"),
        TrackerItem(id: "NE", name: "Niger"),
        TrackerItem(id: "NG", name: "Nigeria"),
        TrackerItem(id: "NU", name: "Niue"),
        TrackerItem(id: "NF", name: "Norfolk Island"),
        TrackerItem(id: "KP", name: "North Korea"),
        TrackerItem(id: "MK", name: "North Macedonia"),
        TrackerItem(id: "MP", name: "Northern Mariana Islands"),
        TrackerItem(id: "NO", name: "Norway"),
        TrackerItem(id: "OM", name: "Oman"),
        TrackerItem(id: "PK", name: "Pakistan"),
        TrackerItem(id: "PW", name: "Palau"),
        TrackerItem(id: "PS", name: "Palestine"),
        TrackerItem(id: "PA", name: "Panama"),
        TrackerItem(id: "PG", name: "Papua New Guinea"),
        TrackerItem(id: "PY", name: "Paraguay"),
        TrackerItem(id: "PE", name: "Peru"),
        TrackerItem(id: "PH", name: "Philippines"),
        TrackerItem(id: "PL", name: "Poland"),
        TrackerItem(id: "PT", name: "Portugal"),
        TrackerItem(id: "PR", name: "Puerto Rico"),
        TrackerItem(id: "QA", name: "Qatar"),
        TrackerItem(id: "RE", name: "Réunion"),
        TrackerItem(id: "RO", name: "Romania"),
        TrackerItem(id: "RU", name: "Russia"),
        TrackerItem(id: "RW", name: "Rwanda"),
        TrackerItem(id: "BL", name: "Saint Barthélemy"),
        TrackerItem(id: "SH", name: "Saint Helena"),
        TrackerItem(id: "KN", name: "Saint Kitts and Nevis"),
        TrackerItem(id: "LC", name: "Saint Lucia"),
        TrackerItem(id: "MF", name: "Saint Martin"),
        TrackerItem(id: "PM", name: "Saint Pierre and Miquelon"),
        TrackerItem(id: "VC", name: "Saint Vincent and the Grenadines"),
        TrackerItem(id: "WS", name: "Samoa"),
        TrackerItem(id: "SM", name: "San Marino"),
        TrackerItem(id: "ST", name: "São Tomé and Príncipe"),
        TrackerItem(id: "SA", name: "Saudi Arabia"),
        TrackerItem(id: "SN", name: "Senegal"),
        TrackerItem(id: "RS", name: "Serbia"),
        TrackerItem(id: "SC", name: "Seychelles"),
        TrackerItem(id: "SL", name: "Sierra Leone"),
        TrackerItem(id: "SG", name: "Singapore"),
        TrackerItem(id: "SX", name: "Sint Maarten"),
        TrackerItem(id: "SK", name: "Slovakia"),
        TrackerItem(id: "SI", name: "Slovenia"),
        TrackerItem(id: "SB", name: "Solomon Islands"),
        TrackerItem(id: "SO", name: "Somalia"),
        TrackerItem(id: "ZA", name: "South Africa"),
        TrackerItem(id: "KR", name: "South Korea"),
        TrackerItem(id: "SS", name: "South Sudan"),
        TrackerItem(id: "ES", name: "Spain"),
        TrackerItem(id: "LK", name: "Sri Lanka"),
        TrackerItem(id: "SD", name: "Sudan"),
        TrackerItem(id: "SR", name: "Suriname"),
        TrackerItem(id: "SE", name: "Sweden"),
        TrackerItem(id: "CH", name: "Switzerland"),
        TrackerItem(id: "SY", name: "Syria"),
        TrackerItem(id: "TW", name: "Taiwan"),
        TrackerItem(id: "TJ", name: "Tajikistan"),
        TrackerItem(id: "TZ", name: "Tanzania"),
        TrackerItem(id: "TH", name: "Thailand"),
        TrackerItem(id: "TL", name: "Timor-Leste"),
        TrackerItem(id: "TG", name: "Togo"),
        TrackerItem(id: "TO", name: "Tonga"),
        TrackerItem(id: "TT", name: "Trinidad and Tobago"),
        TrackerItem(id: "TN", name: "Tunisia"),
        TrackerItem(id: "TR", name: "Turkey"),
        TrackerItem(id: "TM", name: "Turkmenistan"),
        TrackerItem(id: "TC", name: "Turks and Caicos Islands"),
        TrackerItem(id: "TV", name: "Tuvalu"),
        TrackerItem(id: "UG", name: "Uganda"),
        TrackerItem(id: "UA", name: "Ukraine"),
        TrackerItem(id: "AE", name: "United Arab Emirates"),
        TrackerItem(id: "GB", name: "United Kingdom"),
        TrackerItem(id: "US", name: "United States"),
        TrackerItem(id: "UY", name: "Uruguay"),
        TrackerItem(id: "UZ", name: "Uzbekistan"),
        TrackerItem(id: "VU", name: "Vanuatu"),
        TrackerItem(id: "VA", name: "Vatican City"),
        TrackerItem(id: "VE", name: "Venezuela"),
        TrackerItem(id: "VN", name: "Vietnam"),
        TrackerItem(id: "VG", name: "British Virgin Islands"),
        TrackerItem(id: "VI", name: "U.S. Virgin Islands"),
        TrackerItem(id: "EH", name: "Western Sahara"),
        TrackerItem(id: "YE", name: "Yemen"),
        TrackerItem(id: "ZM", name: "Zambia"),
        TrackerItem(id: "ZW", name: "Zimbabwe")
    ].sorted { $0.name < $1.name }

    // MARK: - U.S. States

    static let usStatesOnly: [TrackerItem] = usStates
        .map { TrackerItem(id: "US-\($0.code)", name: $0.name, subtitle: "United States") }
        .sorted { $0.name < $1.name }

    private struct Region {
        let code: String
        let name: String
    }

    private static let usStates: [Region] = [
        Region(code: "AL", name: "Alabama"),
        Region(code: "AK", name: "Alaska"),
        Region(code: "AZ", name: "Arizona"),
        Region(code: "AR", name: "Arkansas"),
        Region(code: "CA", name: "California"),
        Region(code: "CO", name: "Colorado"),
        Region(code: "CT", name: "Connecticut"),
        Region(code: "DE", name: "Delaware"),
        Region(code: "FL", name: "Florida"),
        Region(code: "GA", name: "Georgia"),
        Region(code: "HI", name: "Hawaii"),
        Region(code: "ID", name: "Idaho"),
        Region(code: "IL", name: "Illinois"),
        Region(code: "IN", name: "Indiana"),
        Region(code: "IA", name: "Iowa"),
        Region(code: "KS", name: "Kansas"),
        Region(code: "KY", name: "Kentucky"),
        Region(code: "LA", name: "Louisiana"),
        Region(code: "ME", name: "Maine"),
        Region(code: "MD", name: "Maryland"),
        Region(code: "MA", name: "Massachusetts"),
        Region(code: "MI", name: "Michigan"),
        Region(code: "MN", name: "Minnesota"),
        Region(code: "MS", name: "Mississippi"),
        Region(code: "MO", name: "Missouri"),
        Region(code: "MT", name: "Montana"),
        Region(code: "NE", name: "Nebraska"),
        Region(code: "NV", name: "Nevada"),
        Region(code: "NH", name: "New Hampshire"),
        Region(code: "NJ", name: "New Jersey"),
        Region(code: "NM", name: "New Mexico"),
        Region(code: "NY", name: "New York"),
        Region(code: "NC", name: "North Carolina"),
        Region(code: "ND", name: "North Dakota"),
        Region(code: "OH", name: "Ohio"),
        Region(code: "OK", name: "Oklahoma"),
        Region(code: "OR", name: "Oregon"),
        Region(code: "PA", name: "Pennsylvania"),
        Region(code: "RI", name: "Rhode Island"),
        Region(code: "SC", name: "South Carolina"),
        Region(code: "SD", name: "South Dakota"),
        Region(code: "TN", name: "Tennessee"),
        Region(code: "TX", name: "Texas"),
        Region(code: "UT", name: "Utah"),
        Region(code: "VT", name: "Vermont"),
        Region(code: "VA", name: "Virginia"),
        Region(code: "WA", name: "Washington"),
        Region(code: "WV", name: "West Virginia"),
        Region(code: "WI", name: "Wisconsin"),
        Region(code: "WY", name: "Wyoming"),
        Region(code: "DC", name: "District of Columbia")
    ]

    // MARK: - Continents
    
    static let continents: [TrackerItem] = [
        TrackerItem(id: "AFR", name: "Africa"),
        TrackerItem(id: "ANT", name: "Antarctica"),
        TrackerItem(id: "ASI", name: "Asia"),
        TrackerItem(id: "EUR", name: "Europe"),
        TrackerItem(id: "NAM", name: "North America"),
        TrackerItem(id: "OCE", name: "Oceania"),
        TrackerItem(id: "SAM", name: "South America")
    ]
    
    // MARK: - Subway Systems (curated)
    
    static let subwaySystems: [TrackerItem] = [
        TrackerItem(id: "subway-nyc", name: "New York City Subway", subtitle: "New York, USA"),
        TrackerItem(id: "subway-wmata", name: "Washington Metro", subtitle: "Washington, DC, USA"),
        TrackerItem(id: "subway-boston", name: "MBTA Subway", subtitle: "Boston, USA"),
        TrackerItem(id: "subway-chicago", name: "Chicago 'L'", subtitle: "Chicago, USA"),
        TrackerItem(id: "subway-bart", name: "BART", subtitle: "San Francisco Bay Area, USA"),
        TrackerItem(id: "subway-muni", name: "Muni Metro", subtitle: "San Francisco, USA"),
        TrackerItem(id: "subway-la", name: "LA Metro Rail", subtitle: "Los Angeles, USA"),
        TrackerItem(id: "subway-septa", name: "SEPTA Metro", subtitle: "Philadelphia, USA"),
        TrackerItem(id: "subway-marta", name: "MARTA Rail", subtitle: "Atlanta, USA"),
        TrackerItem(id: "subway-miami", name: "Metrorail", subtitle: "Miami, USA"),
        
        TrackerItem(id: "subway-toronto", name: "Toronto Subway", subtitle: "Toronto, Canada"),
        TrackerItem(id: "subway-montreal", name: "Montréal Metro", subtitle: "Montréal, Canada"),
        TrackerItem(id: "subway-vancouver", name: "SkyTrain", subtitle: "Vancouver, Canada"),
        
        TrackerItem(id: "subway-london", name: "London Underground", subtitle: "London, UK"),
        TrackerItem(id: "subway-paris", name: "Paris Métro", subtitle: "Paris, France"),
        TrackerItem(id: "subway-berlin", name: "Berlin U-Bahn", subtitle: "Berlin, Germany"),
        TrackerItem(id: "subway-munich", name: "Munich U-Bahn", subtitle: "Munich, Germany"),
        TrackerItem(id: "subway-vienna", name: "Vienna U-Bahn", subtitle: "Vienna, Austria"),
        TrackerItem(id: "subway-madrid", name: "Metro de Madrid", subtitle: "Madrid, Spain"),
        TrackerItem(id: "subway-barcelona", name: "Barcelona Metro", subtitle: "Barcelona, Spain"),
        TrackerItem(id: "subway-rome", name: "Rome Metro", subtitle: "Rome, Italy"),
        TrackerItem(id: "subway-milan", name: "Milan Metro", subtitle: "Milan, Italy"),
        TrackerItem(id: "subway-lisbon", name: "Lisbon Metro", subtitle: "Lisbon, Portugal"),
        TrackerItem(id: "subway-amsterdam", name: "Amsterdam Metro", subtitle: "Amsterdam, Netherlands"),
        TrackerItem(id: "subway-brussels", name: "Brussels Metro", subtitle: "Brussels, Belgium"),
        TrackerItem(id: "subway-stockholm", name: "Stockholm Metro", subtitle: "Stockholm, Sweden"),
        TrackerItem(id: "subway-copenhagen", name: "Copenhagen Metro", subtitle: "Copenhagen, Denmark"),
        TrackerItem(id: "subway-oslo", name: "Oslo Metro", subtitle: "Oslo, Norway"),
        TrackerItem(id: "subway-helsinki", name: "Helsinki Metro", subtitle: "Helsinki, Finland"),
        TrackerItem(id: "subway-warsaw", name: "Warsaw Metro", subtitle: "Warsaw, Poland"),
        TrackerItem(id: "subway-prague", name: "Prague Metro", subtitle: "Prague, Czechia"),
        TrackerItem(id: "subway-budapest", name: "Budapest Metro", subtitle: "Budapest, Hungary"),
        
        TrackerItem(id: "subway-moscow", name: "Moscow Metro", subtitle: "Moscow, Russia"),
        TrackerItem(id: "subway-spb", name: "Saint Petersburg Metro", subtitle: "Saint Petersburg, Russia"),
        TrackerItem(id: "subway-istanbul", name: "Istanbul Metro", subtitle: "Istanbul, Turkey"),
        TrackerItem(id: "subway-athens", name: "Athens Metro", subtitle: "Athens, Greece"),
        TrackerItem(id: "subway-dubai", name: "Dubai Metro", subtitle: "Dubai, UAE"),
        TrackerItem(id: "subway-doha", name: "Doha Metro", subtitle: "Doha, Qatar"),
        
        TrackerItem(id: "subway-tokyo", name: "Tokyo Metro", subtitle: "Tokyo, Japan"),
        TrackerItem(id: "subway-toei", name: "Toei Subway", subtitle: "Tokyo, Japan"),
        TrackerItem(id: "subway-seoul", name: "Seoul Subway", subtitle: "Seoul, South Korea"),
        TrackerItem(id: "subway-hk", name: "MTR", subtitle: "Hong Kong"),
        TrackerItem(id: "subway-singapore", name: "MRT", subtitle: "Singapore"),
        TrackerItem(id: "subway-taipei", name: "Taipei Metro", subtitle: "Taipei, Taiwan"),
        TrackerItem(id: "subway-beijing", name: "Beijing Subway", subtitle: "Beijing, China"),
        TrackerItem(id: "subway-shanghai", name: "Shanghai Metro", subtitle: "Shanghai, China"),
        
        TrackerItem(id: "subway-mexicocity", name: "Mexico City Metro", subtitle: "Mexico City, Mexico"),
        TrackerItem(id: "subway-saopaulo", name: "São Paulo Metro", subtitle: "São Paulo, Brazil"),
        TrackerItem(id: "subway-buenosaires", name: "Buenos Aires Subte", subtitle: "Buenos Aires, Argentina"),
        TrackerItem(id: "subway-santiago", name: "Santiago Metro", subtitle: "Santiago, Chile")
    ]

    // MARK: - US National Parks

    static let usNationalParks: [TrackerItem] = [
        TrackerItem(id: "nps-acadia", name: "Acadia"),
        TrackerItem(id: "nps-americansamoa", name: "American Samoa"),
        TrackerItem(id: "nps-arches", name: "Arches"),
        TrackerItem(id: "nps-badlands", name: "Badlands"),
        TrackerItem(id: "nps-bigs", name: "Big Bend"),
        TrackerItem(id: "nps-biscayne", name: "Biscayne"),
        TrackerItem(id: "nps-blackcanyon", name: "Black Canyon of the Gunnison"),
        TrackerItem(id: "nps-bryce", name: "Bryce Canyon"),
        TrackerItem(id: "nps-canyonlands", name: "Canyonlands"),
        TrackerItem(id: "nps-capitolreef", name: "Capitol Reef"),
        TrackerItem(id: "nps-carlsbad", name: "Carlsbad Caverns"),
        TrackerItem(id: "nps-channelislands", name: "Channel Islands"),
        TrackerItem(id: "nps-congaree", name: "Congaree"),
        TrackerItem(id: "nps-craterlake", name: "Crater Lake"),
        TrackerItem(id: "nps-cuyahoga", name: "Cuyahoga Valley"),
        TrackerItem(id: "nps-deathvalley", name: "Death Valley"),
        TrackerItem(id: "nps-denali", name: "Denali"),
        TrackerItem(id: "nps-dry", name: "Dry Tortugas"),
        TrackerItem(id: "nps-everglades", name: "Everglades"),
        TrackerItem(id: "nps-gates", name: "Gates of the Arctic"),
        TrackerItem(id: "nps-gatewayarch", name: "Gateway Arch"),
        TrackerItem(id: "nps-glacier", name: "Glacier"),
        TrackerItem(id: "nps-glacierbay", name: "Glacier Bay"),
        TrackerItem(id: "nps-grandcanyon", name: "Grand Canyon"),
        TrackerItem(id: "nps-grandteton", name: "Grand Teton"),
        TrackerItem(id: "nps-greatbasin", name: "Great Basin"),
        TrackerItem(id: "nps-greatsanddunes", name: "Great Sand Dunes"),
        TrackerItem(id: "nps-greatsmoky", name: "Great Smoky Mountains"),
        TrackerItem(id: "nps-guadalupe", name: "Guadalupe Mountains"),
        TrackerItem(id: "nps-haleakala", name: "Haleakalā"),
        TrackerItem(id: "nps-hawaii", name: "Hawaiʻi Volcanoes"),
        TrackerItem(id: "nps-hot", name: "Hot Springs"),
        TrackerItem(id: "nps-isle", name: "Isle Royale"),
        TrackerItem(id: "nps-joshua", name: "Joshua Tree"),
        TrackerItem(id: "nps-katmai", name: "Katmai"),
        TrackerItem(id: "nps-kenai", name: "Kenai Fjords"),
        TrackerItem(id: "nps-kings", name: "Kings Canyon"),
        TrackerItem(id: "nps-kobuk", name: "Kobuk Valley"),
        TrackerItem(id: "nps-lassen", name: "Lassen Volcanic"),
        TrackerItem(id: "nps-mammoth", name: "Mammoth Cave"),
        TrackerItem(id: "nps-mesa", name: "Mesa Verde"),
        TrackerItem(id: "nps-mount", name: "Mount Rainier"),
        TrackerItem(id: "nps-northcascades", name: "North Cascades"),
        TrackerItem(id: "nps-olympic", name: "Olympic"),
        TrackerItem(id: "nps-petrified", name: "Petrified Forest"),
        TrackerItem(id: "nps-pinnacles", name: "Pinnacles"),
        TrackerItem(id: "nps-redwood", name: "Redwood"),
        TrackerItem(id: "nps-rocky", name: "Rocky Mountain"),
        TrackerItem(id: "nps-saguaro", name: "Saguaro"),
        TrackerItem(id: "nps-sequoia", name: "Sequoia"),
        TrackerItem(id: "nps-shenandoah", name: "Shenandoah"),
        TrackerItem(id: "nps-theodore", name: "Theodore Roosevelt"),
        TrackerItem(id: "nps-virgin", name: "Virgin Islands"),
        TrackerItem(id: "nps-voyageurs", name: "Voyageurs"),
        TrackerItem(id: "nps-white", name: "White Sands"),
        TrackerItem(id: "nps-wind", name: "Wind Cave"),
        TrackerItem(id: "nps-wrangell", name: "Wrangell–St. Elias"),
        TrackerItem(id: "nps-yellowstone", name: "Yellowstone"),
        TrackerItem(id: "nps-yosemite", name: "Yosemite"),
        TrackerItem(id: "nps-zion", name: "Zion"
        )
    ].sorted { $0.name < $1.name }
}

